services:
  - type: web
    name: pr-sistemas-base-conhecimento
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: PGSSL
        value: true
      - key: UNIT_VERSIONS_SYNC_INTERVAL_MS
        value: 300000
